config/routes.rb
Rails.application.routes.draw do
  root 'dishes#index'
  
  resources :dishes  
  resources :categories
  resources :daily_menu
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :dishes
end

app/models/daily_menu.rb
class DailyMenu < ApplicationRecord
  serialize :menu, Array  
end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]


  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:category)
    end
end

app/controllers/daily_menu_controller.rb
class DailyMenuController < ApplicationController
  def index
  end

  def show
  end

  def new
    @categories = Category.all
    @dishes = Dish.all

    # debugger
    @menu = DailyMenu.create()
  end

  def edit
  end

  # private

  # def daily_menu_params
  #   params.require(:daily_menu).permit(:date, menu:[])
  # end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: %i[update show destroy edit]

  def create
   @dish = Dish.create(dish_params)

    # Category.create(dish_name: dish[:name], dish_id: dish[:id], category_type: dish[:category_type])

    flash


    if @dish.save
      redirect_to @dish
    else
      render :new
    end
    # redirect_to dish_path(dish)
    # redirect_to dish, notice: 'dish was created'
  end

  def update
    @dish.update(dish_params)

    redirect_to dish_path(@dish), notice: 'dish was updated'
  end

  def destroy
    @dish.destroy

    redirect_to dishes_path, notice: 'dish was deleted'
  end

  def show
  end

  def index
    @categories = Category.all
    @dishes = Dish.all

  end

  def new
    @dish = Dish.new
  end

  def edit
  end

  private

  def dish_params
    params.require(:dish).permit(:name, :price_type, :price, :category_id)
  end

  def set_dish
    @dish = Dish.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/daily_menu_helper.rb
module DailyMenuHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Category:</strong>
    <%= category.category %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/daily_menu/edit.html.erb
<h1>DailyMenu#edit</h1>
<p>Find me in app/views/daily_menu/edit.html.erb</p>

app/views/daily_menu/index.html.erb
<h1>DailyMenu#index</h1>
<p>Find me in app/views/daily_menu/index.html.erb</p>

app/views/daily_menu/new.html.erb
<h1>New Daily Menu</h1>

<%= form_with model: @daily_menu do |f| %>
  <%= f.label :date %>
  <%= f.date_field :date %>

  <div class='my-2'> <%= f.label 'add to menu?' %></div>
  <% @categories.map do |c| %>
    <h5> <%= c.category %> </h5>
    <% filtred = @dishes.filter{|d| d.category_id == c.id}%>
        <% filtred.each do |item| %>
        <%= f.check_box(item.name) %>
        <%= f.label(item.name) %>
      <% end %> 
     <%# <%= f.collection_check_boxes :menu, filtred, :id, :name %> 
  <% end %>
  <div class='my-3'><%= f.submit 'Save', class: 'btn btn-info' %></div>
<% end %>






       



      %>

app/views/daily_menu/show.html.erb
<h1>DailyMenu#show</h1>
<p>Find me in app/views/daily_menu/show.html.erb</p>

app/views/dishes/_form.html.erb
  <%= form_with model: @dish do |form| %>
    <div class="form-group mt-3 w-25">
      <div class='mt-2'> <%= form.label :name %> </div>
      <div> <%= form.text_field :name, class: 'form-control' %> </div>

      <div class='mt-2'> <%= form.label :category_id %> 
       <%= form.select :category_id, Category.all.map{|c| [c.category,c.id]}, class: 'form-control' %> </div>

      <div class='mt-2 '> <%= form.label :price_type %> 
       <%= form.select :price_type, ['by weight', 'by item'], class: 'form-control' %> </div>

      <div class='mt-2'> <%= form.label :price %> </div>
      <div> <%= form.text_field :price, class: 'form-control'%> </div> 

      <div class='my-3'><%= form.submit 'Save', class: 'btn btn-info' %></div>
    </div>
  <% end %>
  
  
  <%# ['Garnish', 'Salad', 'Soups', 'Pizza'] %>

app/views/dishes/edit.html.erb
<h2 class='text-center'>Edit<%= @dish.name %></h2>

<%= render 'form', dish: @dish %>

<%= link_to "Back to dish", dish_path %>
<div class='mt-3'>
  <%= link_to "Back to list", dishes_path %>
</div>

app/views/dishes/index.html.erb
<div class="row">
  <h1 class='text-center mb-5'>
    Daily Menu
    <%# <br> %>
    <%= Date.today.strftime("%e %b %Y") %>
  </h1>
  <div class='col-8 '>
  <div class="card">
    <div class="card-header d-flex">
       <h2>  Dishes   </h2>
        <%= link_to "➕", new_dish_path, class: 'text-decoration-none' %>
    </div>
     <div class="d-flex gap-3 m-3 ">
         <% @dishes.each_with_index do |dish, index|%>

          <div class=' card flex-row justify-content-around p-2'>
            <div class="card-title h5 mb-0"> <%= dish.name.capitalize %></div>
            <div class="mx-2">
               <%= link_to 'i', dish_path(dish.id), class: 'text-decoration-none font-weight-bold' %>
            </div>
           
          </div>
      <% end %>

     </div>
  </div>
  


  </div>

  <div class='col-4'>
    <div class="card">
      <div class="card-header d-flex ">
        <h2> Categories </h2>
        <%= link_to "➕", new_category_path, class: 'text-decoration-none' %>
      </div>

        <div class="d-flex gap-3 m-3">
          <% @categories.each do |category| %>
            <button type="button" class="btn btn-outline-primary position-relative p-2">
              <%= link_to category.category, class: "text-decoration-none" %>
              <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-primary">
                <%= category.dishes.count %>
              </span>
            </button>
          <% end %>
        </div>
    </div>
  </div>

  </div>

app/views/dishes/new.html.erb
<h2 class='text-center '> create new dish</h2>
<%= render 'form', dish: @dish %>
<div class='mt-3'>
  <%= link_to "Back to list", dishes_path %>
</div>

app/views/dishes/show.html.erb
<h2 class='text-center mt-5'>Dish Details</h2>
<div class='p-3 card'>
  <div>
    <b>Name: </b>
    <%=@dish.name.capitalize %> 
  </div>

  <div>
    <b>Price: </b>
    <%= @dish.price%> 
  </div>

  <div>
    <b>Category: </b>
    <%= @dish.category.category%> 
  </div>

  <div>
    <b>Price type: </b>
    <%= @dish.price_type %> 
  </div>
  
  <div class='mt-1'>
    <%= button_to 'Delete', dish_path, method: :delete %>
  </div>
  
  <div class='mt-3'>
    <%= link_to "Edit", edit_dish_path %>
  </div>
    <%= link_to "Back to list", dishes_path %>

</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Daily Menu Rails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class='container mt-5'>
      <% if flash[:notice].present? %>
        <p class='text-center mt-3 alert alert-warning alert-dismissible fade show'>
          <%= flash[:notice]%>
        </p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>